require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rentacop:
    - rentacop.yml
    - rspec.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - 'debug.rb'
    - 'dev/**/*'

# Allow `Marshal.load`, since we want to get the Ruby object from cache
# We assume trusted source for all caching operations
Security/MarshalLoad:
  Enabled: false
